### ISSUE TITLE
REQUEST: Allow side input/output for machines

### ISSUE THREAD

**Issue by kwpugh** [oitsjustjose/CrissCross#1]
It would be great if the machines could pull/push with chests and the vanilla furnace.

**Comment by oitsjustjose** [comment]
It would be, yes, but the idea of CrissCross is to closely reflect the game mechanics of existing Vanilla blocks. I feel like this feature would take away from that, as you've already got to manually (or automatically via hoppers) fuel my machinery anyways. I'll look into it, but no promises as to if this will ever be a thing. Maybe if I get around to implementing a branch of CrissCross machinery that takes RF or EU (or... EF? I think that's Extra Utilities 2's new "energy system"). If I decide to do that, I'll more than likely work on better ISided integration :)
