### ISSUE TITLE
Infiniapple Server Crash

### ISSUE THREAD

**Issue by MisterShawn** [oitsjustjose/CrissCross#5]
Was on my server and cheated in the infiniapple to see it's function (was guessing it was unlimited food) and the server crashed. Thankfully you added the ability to disable it in the config :-D

Crash report: http://hastebin.com/raw/iyevidasug

**Comment by oitsjustjose** [comment]
Fixed this - not sure why saturation isn't modifiable on the server, but is accessible by the server...

Regardless, saturation didn't actually do anything anyways! :)
